INSERT INTO USERS (name,pass) VALUES ('user1','p@ss1');
INSERT INTO USERS (name,pass) VALUES ('user2','p@ss2');
INSERT INTO USERS (name,pass) VALUES ('user3','p@ss3');
INSERT INTO USERS (name,pass) VALUES ('user4','p@ss4');
INSERT INTO USERS (name,pass) VALUES ('teacher','oit');
INSERT INTO ITEMS (name) VALUES ('りんご');
INSERT INTO ITEMS (name) VALUES ('みかん');
INSERT INTO ITEMS (name) VALUES ('ぶどう');
INSERT INTO AUCTION (itemId, sellerId, maxBid, date, bidderId) VALUES (2, 3, 1122, '2021-12-12',1);
INSERT INTO AUCTION (itemId, sellerId, maxBid, date) VALUES (3, 1, NULL, '2021-12-13');
INSERT INTO AUCTION (itemId, sellerId, maxBid, date) VALUES (3, 1, NULL, '2022-12-13');
