CREATE TABLE USERS(
  id IDENTITY,
  name CHAR NOT NULL,
  money INT NOT NULL,
  pass CHAR NOT NULL,
  login DATE NOT NULL
);

CREATE TABLE AUCTION(
  id IDENTITY,
  itemId INT NOT NULL,
  sellerId INT NOT NULL,
  maxBid INT,
  date DATE NOT NULL,
  bidderId INT
);

CREATE TABLE ITEMS(
  id IDENTITY,
  name CHAR NOT NULL
);

CREATE TABLE AWARDS(
  id IDENTITY,
  bidderId INT NOT NULL,
  itemId INT NOT NULL
);
